# Generated by Django 5.2.5 on 2026-06-12 12:19

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.fields
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0210_macaddress_ordering'),
        ('extras', '0129_fix_script_paths'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200)),
                ('trigramme', models.CharField(blank=True, db_index=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('editor', models.CharField(blank=True, max_length=100)),
                ('referent', models.CharField(blank=True, max_length=100)),
                ('hosting', models.CharField(blank=True, max_length=100)),
                ('criticality', models.CharField(default='standard', max_length=30)),
                ('multi_site', models.BooleanField(default=False)),
                ('monitoring_url', models.URLField(blank=True)),
                ('interface_administrative', models.BooleanField(default=False)),
                ('interface_medicale', models.BooleanField(default=False)),
                ('interface_facturation', models.BooleanField(default=False)),
                ('interface_planification', models.BooleanField(default=False)),
                ('interface_autre', models.BooleanField(default=False)),
                ('devices', models.ManyToManyField(blank=True, related_name='it_landscape_applications', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtual_machines', models.ManyToManyField(blank=True, related_name='it_landscape_applications', to='virtualization.virtualmachine')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ApplicationFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('flow_id', models.CharField(blank=True, max_length=50)),
                ('protocol', models.CharField(blank=True, max_length=50)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('message_type', models.CharField(blank=True, max_length=50)),
                ('interface_type', models.CharField(default='autre', max_length=30)),
                ('eai', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows_as_source', to='netbox_it_landscape.application')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows_as_target', to='netbox_it_landscape.application')),
            ],
            options={
                'verbose_name': 'flux applicatif',
                'verbose_name_plural': 'flux applicatifs',
                'ordering': ('flow_id', 'source', 'target'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BusinessDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('color', utilities.fields.ColorField(default='e5f4fd', max_length=6)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_domains', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'domaine métier',
                'verbose_name_plural': 'domaines métier',
                'ordering': ('site', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='netbox_it_landscape.businessdomain')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'processus métier',
                'verbose_name_plural': 'processus métier',
                'ordering': ('domain', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='application',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='netbox_it_landscape.businessprocess'),
        ),
        migrations.AddConstraint(
            model_name='businessdomain',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='netbox_it_landscape_businessdomain_unique_site_name'),
        ),
        migrations.AddConstraint(
            model_name='businessprocess',
            constraint=models.UniqueConstraint(fields=('domain', 'name'), name='netbox_it_landscape_businessprocess_unique_domain_name'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('process', 'name'), name='netbox_it_landscape_application_unique_process_name'),
        ),
    ]
