# Generated by Django 5.2.5 on 2026-06-12 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0210_macaddress_ordering'),
        ('netbox_it_landscape', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='netbox_it_landscape_application_unique_process_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='multi_site',
        ),
        migrations.RemoveField(
            model_name='application',
            name='process',
        ),
        migrations.RemoveField(
            model_name='application',
            name='trigramme',
        ),
        migrations.AddField(
            model_name='application',
            name='processes',
            field=models.ManyToManyField(blank=True, related_name='applications', to='netbox_it_landscape.businessprocess'),
        ),
        migrations.AddField(
            model_name='applicationflow',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_flows', to='dcim.site'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
